### ISSUE TITLE
Connection refused, yet other rcon tools work fine.

### ISSUE THREAD

**Issue by piousminion** [barneygale/MCRcon#5]
I can use other RCON tools to run commands/query my server, but with your demo.py, I get the following. Please let me know if there is any other information I can provide to aide in solving this issue.

[root@<omitted>]# python rcon.py 127.0.0.1 32571 <omitted>
\# connecting to 127.0.0.1:32571...
Traceback (most recent call last):
  File "rcon.py", line 39, in <module>
    main(host, port, password)
  File "rcon.py", line 13, in main
    rcon.connect(host, port)
  File "/root/bin/mcrcon.py", line 14, in connect
    self.socket.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
[root@<omitted>]#

**Comment by piousminion** [comment]
Scratch that. It works flawlessly when specifying the external IP that the server is listening on. :P
