### ISSUE TITLE
struct.error: unpack requires a bytes object of length 4

### ISSUE THREAD

**Issue by MaxValue** [barneygale/MCRcon#8]
I always get this error, password length is 20:

```
Traceback (most recent call last):
  File "demo.py", line 39, in <module>
    main(host, port, password)
  File "demo.py", line 16, in main
    rcon.login(password)
  File "C:\Data\username\Data\MCRcon-master\MCRcon-master\mcrcon.py", line 55, in login
    return self.send(3, password)
  File "C:\Data\username\Data\MCRcon-master\MCRcon-master\mcrcon.py", line 33, in send
    in_length, = struct.unpack('<i', self.socket.recv(4))
struct.error: unpack requires a bytes object of length 4
```

It occurs for python2 and for python3. Do you experience the same?

**Comment by barneygale** [comment]
Pushed a potential fix for this in 3558bf09cbb4c3bd0f78ac0d183b9383b22f556f, could you give it a try?

**Comment by MaxValue** [comment]
I compared the 2 versions and interestingly they both throw the same Exception now. Not this one, but a different one:

old:
```
Traceback (most recent call last):
  File "demo.py", line 39, in <module>
    main(host, port, password)
  File "demo.py", line 13, in main
    rcon.connect(host, port)
  File "C:\Data\username\Data\MCRcon-master\old\mcrcon.py", line 14, in connect
    self.socket.connect((host, port))
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
Traceback (most recent call last):
  File "demo.py", line 39, in <module>
    main(host, port, password)
  File "demo.py", line 13, in main
    rcon.connect(host, port)
  File "C:\Data\username\Data\MCRcon-master\old\mcrcon.py", line 14, in connect
    self.socket.connect((host, port))
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
```

new:
```
Traceback (most recent call last):
  File "demo.py", line 39, in <module>
    main(host, port, password)
  File "demo.py", line 13, in main
    rcon.connect(host, port)
  File "C:\Data\username\Data\MCRcon-master\new\mcrcon.py", line 14, in connect
    self.socket.connect((host, port))
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
```

This time the targeted server is not up, therefore maybe the error.
Last time i haven't added the port forwarding rule for 25575 yet. Could be that the router answered something which resulted in the very first error.

**Comment by barneygale** [comment]
If the server's not up then yeah, `socket.connect` will throw an error.

**Comment by barneygale** [comment]
I think the original problem is now fixed; if you run into any more trouble please log another issue! Thanks.
